name: Personalized Greeting

on:
  schedule:
    - cron: "6 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Personalized Greeting
        id: greeting
        uses: actions/checkout@v2
      - name: Set Greeting
        run: |
          time=$(date +"%T")
          hour=${time:0:2}
          if [[ $hour -ge 5 && $hour -lt 12 ]]; then
            sed -i 's|<morning-greeting>|Good morning, ${{ github.actor }}!|' README.md
          elif [[ $hour -ge 12 && $hour -lt 17 ]]; then
            sed -i 's|<morning-greeting>|Good afternoon, ${{ github.actor }}!|' README.md
          else
            sed -i 's|<morning-greeting>|Good evening, ${{ github.actor }}!|' README.md
          fi
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'CharlesKasasira'
          git config --global user.email 'charleskasasira01@gmail.com'
          git commit -am "Update greeting in README"
          git push
